FROM quay.io/fedora/fedora:40

# Base stuff
RUN dnf -y install \
        git \
        rsync \
        patch

# Install deps
RUN dnf -y install \
        ldc \
        dub

# Run deps
RUN dnf -y install \
        cairo \
        blend2d
